### ISSUE TITLE
토론 작성중 Unexpected end of JSON input 오류 발생

### ISSUE THREAD

**Issue by ysw827** [gamramstone-dev/gamramstone#19]
![image](https://user-images.githubusercontent.com/72365216/208894691-cf7c990d-8733-4f3a-862f-0fdee9bfd081.png)
이런식으로 뜨면서 토론이 작성되지 않습니다
내용 :
[싱크 대기 목록.txt](https://github.com/gamramstone-dev/gamramstone/files/10277219/default.txt)

**Comment by So-chiru** [comment]
내용이 너무 길어서 오류뜨는 것 같네요, 내용 줄여서 다시 시도해보세요

**Comment by ysw827** [comment]
알겠습니다
